### ISSUE TITLE
Availability is being ignored (or timezones are off)

### ISSUE THREAD

**Issue by dmonn** [calendso/calendso#1437]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

I've set up my global availability after 10am  (GMT+1). The event availability itself starts at 9am (GMT+1). When I go to my scheduling, users can book times starting at 8am (GMT+1).

![Screenshot 2022-01-10 at 08 56 52](https://user-images.githubusercontent.com/6407031/148733809-5a21e284-e00d-47ce-963e-f5135a14e6ef.png)

![Screenshot 2022-01-10 at 08 57 00](https://user-images.githubusercontent.com/6407031/148733818-de2b54e4-3c2a-43d4-a0e1-e20168d0efad.png)

![Screenshot 2022-01-10 at 08 57 09](https://user-images.githubusercontent.com/6407031/148733826-f599a8d8-a294-4e48-b170-e21ba9acf498.png)

### Steps to Reproduce

Using GMT+1 everywhere

1. Set up global availability to 10am
2. Set up event availability to 9am
3. Check when event is actually available

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

- Browser version: https://www.whatsmybrowser.org/b/KRHWO
- Node.js version: Hosted cal.com
- Anything else that you think could be an issue: My account cal.com/dom/ also suffered from #1236 which is not un-related

**Comment by manjufy** [comment]
Same issue as https://github.com/calendso/calendso/issues/1427

**Comment by emrysal** [comment]
@dmonn Could you confirm this been fixed by #1488?

**Comment by manjufy** [comment]
@dmonn is the code been rebased with your SaaS version.
I can take a look into it, if its still not working.

**Comment by dmonn** [comment]
It runs on your SaaS (cal.com), so no idea what the version on there is right now. Included link in message above, still not working as of today.

**Comment by manjufy** [comment]
Interesting.
I have pulled the latest codes and tested them. Yes, @dmonn there seems to be a bit of odd behaviour.

It seems to work well if you set global availability (From Availability tab), However, if you have a global availability set, together with event-based availability, slots are completely off, I do not even understand how the slots are calculated 😅.

![photo6287123499441041408](https://user-images.githubusercontent.com/5035624/150151704-7e4400fb-9815-4144-8906-8d0e58ebabd7.jpg)


![photo6287123499441041409](https://user-images.githubusercontent.com/5035624/150151714-4d7d6edd-05dd-4f38-a00e-c5a8172f284a.jpg) 

However, when I override the availability in the event type, here is what I see
![photo6287123499441041411](https://user-images.githubusercontent.com/5035624/150151885-77299139-1cca-452c-8f91-8f571e57182d.jpg)

![photo6287123499441041410](https://user-images.githubusercontent.com/5035624/150151877-40d1d6d5-8593-4f14-9739-2e8947b92c94.jpg)

**Comment by carlosrojas** [comment]
My default time zone is GMT-8. As stated above, when I set the global availability it works just as intended. When I set event availability I can only get my availability to show correctly if I set the event timezone to UTC, but my availability can’t be set past 4pm. If I go past 4pm my availability doesn’t make sense. I assume it stops working after 4pm because that’s when UTC transitions to the next day when comparing with GMT-8.  

I hope that helps.

**Comment by MarthoxGT** [comment]
Greetings @emrysal !!
I just submitted a PR that I think solves this problem, so feel free to give it a look, any feedback is aprecciated.
